# Generated by Django 3.2.9 on 2021-11-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=355)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
